# Generated by Django 4.1.7 on 2023-04-06 11:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('registered_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('response_date', models.DateField(default=datetime.datetime(2023, 4, 7, 11, 2, 44, 761346))),
                ('completed', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(blank=True, related_name='postlike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('like', 'like'), ('unlike', 'unlike')], default='Like', max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complainapp.complain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('designation_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_holder', to='complainapp.profile')),
                ('parent', models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, to='complainapp.designation')),
            ],
        ),
        migrations.AddField(
            model_name='complain',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complainapp.profile'),
        ),
        migrations.AddField(
            model_name='complain',
            name='registered_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complainapp.designation'),
        ),
    ]
