# Generated by Django 4.1.7 on 2023-04-24 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complainapp', '0004_alter_complain_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='response_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 7, 52, 59, 87307)),
        ),
    ]
